config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :mathematics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mathematic.rb
class Mathematic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mathematics_controller.rb
class MathematicsController < ApplicationController
  before_action :set_mathematic, only: [:show, :edit, :update, :destroy]

  # GET /mathematics
  # GET /mathematics.json
  def index
    @mathematics = Mathematic.all
  end

  # GET /mathematics/1
  # GET /mathematics/1.json
  def show
  end

  # GET /mathematics/new
  def new
    @mathematic = Mathematic.new
  end

  # GET /mathematics/1/edit
  def edit
  end

  # POST /mathematics
  # POST /mathematics.json
  def create
    @mathematic = Mathematic.new(mathematic_params)

    respond_to do |format|
      if @mathematic.save
        format.html { redirect_to @mathematic, notice: 'Mathematic was successfully created.' }
        format.json { render :show, status: :created, location: @mathematic }
      else
        format.html { render :new }
        format.json { render json: @mathematic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mathematics/1
  # PATCH/PUT /mathematics/1.json
  def update
    respond_to do |format|
      if @mathematic.update(mathematic_params)
        format.html { redirect_to @mathematic, notice: 'Mathematic was successfully updated.' }
        format.json { render :show, status: :ok, location: @mathematic }
      else
        format.html { render :edit }
        format.json { render json: @mathematic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mathematics/1
  # DELETE /mathematics/1.json
  def destroy
    @mathematic.destroy
    respond_to do |format|
      format.html { redirect_to mathematics_url, notice: 'Mathematic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mathematic
      @mathematic = Mathematic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mathematic_params
      params.require(:mathematic).permit(:title, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mathematics_helper.rb
module MathematicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mathematics/_form.html.erb
<%= form_for(mathematic) do |f| %>
  <% if mathematic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mathematic.errors.count, "error") %> prohibited this mathematic from being saved:</h2>

      <ul>
      <% mathematic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mathematics/edit.html.erb
<h1>Editing Mathematic</h1>

<%= render 'form', mathematic: @mathematic %>

<%= link_to 'Show', @mathematic %> |
<%= link_to 'Back', mathematics_path %>

app/views/mathematics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mathematics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mathematics.each do |mathematic| %>
      <tr>
        <td><%= mathematic.title %></td>
        <td><%= mathematic.message %></td>
        <td><%= link_to 'Show', mathematic %></td>
        <td><%= link_to 'Edit', edit_mathematic_path(mathematic) %></td>
        <td><%= link_to 'Destroy', mathematic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mathematic', new_mathematic_path %>

app/views/mathematics/new.html.erb
<h1>New Mathematic</h1>

<%= render 'form', mathematic: @mathematic %>

<%= link_to 'Back', mathematics_path %>

app/views/mathematics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mathematic.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @mathematic.message %>
</p>

<%= link_to 'Edit', edit_mathematic_path(@mathematic) %> |
<%= link_to 'Back', mathematics_path %>